[maliit]
onscreen\active=liblomiri-keyboard-plugin.so:en
onscreen\enabled=liblomiri-keyboard-plugin.so:en
pluginsettings\liblomiri-keyboard-plugin.so\current_style=lomiri
pluginsettings\liblomiri-keyboard-plugin.so\word_engine_enabled=false
